import Link from "next/link"
import Image from "next/image"

export const metadata = {
  title: "Terms of Service - TheStudentBlueprint",
  description: "Terms of Service for TheStudentBlueprint assessment platform",
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#faf8f3] font-sans">
      <nav className="bg-[#0a192f] py-6">
        <div className="max-w-4xl mx-auto px-6 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3 group">
            <div className="relative w-8 h-8 transition-transform duration-700 group-hover:rotate-[360deg]">
              <Image src="/logo.png" alt="Logo" fill className="object-contain" />
            </div>
            <span className="text-xl font-bold text-white tracking-tight" style={{ fontFamily: "'Playfair Display', serif" }}>
              TheStudentBlueprint
            </span>
          </Link>
          <Link href="/" className="text-xs text-white/50 hover:text-[#c9a227] uppercase tracking-widest font-bold transition-colors">
            Back to Home
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold text-[#0a192f] mb-2" style={{ fontFamily: "'Playfair Display', serif" }}>
          Terms of Service
        </h1>
        <p className="text-sm text-[#0a192f]/40 uppercase tracking-widest font-bold mb-12">
          Last updated: January 2026
        </p>

        <div className="prose prose-lg max-w-none text-[#0a192f]/70 space-y-8">
          <section>
            <h2 className="text-xl font-bold text-[#0a192f] mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using TheStudentBlueprint platform (&quot;Service&quot;), you agree to be bound by these Terms of Service. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a192f] mb-3">2. Description of Service</h2>
            <p>TheStudentBlueprint provides a multi-tenant student assessment platform that enables educational consulting agencies to offer AI-powered college admissions roadmaps to their students. The Service includes student assessments, AI-generated analysis, report generation, and agency management tools.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a192f] mb-3">3. Agency Accounts</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>Agency accounts are created upon approval by TheStudentBlueprint team.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You must not share account access with unauthorized individuals.</li>
              <li>You are responsible for all activities that occur under your account.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a192f] mb-3">4. Subscription & Billing</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>Subscription plans are billed monthly through Stripe.</li>
              <li>Free trials, when offered, automatically convert to paid subscriptions unless cancelled.</li>
              <li>You may cancel your subscription at any time through the billing portal.</li>
              <li>Refunds are handled on a case-by-case basis.</li>
              <li>Student assessment fees are set by each agency and collected through the platform.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a192f] mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-3">
              <li>Use the Service for any unlawful purpose.</li>
              <li>Submit false or misleading student information.</li>
              <li>Attempt to reverse-engineer, decompile, or interfere with the platform.</li>
              <li>Exceed your subscription plan limits without upgrading.</li>
              <li>Share API keys or allow unauthorized access to your account.</li>
              <li>Use the AI-generated analysis as the sole basis for admissions decisions.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a192f] mb-3">6. AI-Generated Content</h2>
            <p>The student assessments, archetype classifications, roadmaps, and college recommendations generated by our platform are powered by artificial intelligence and should be used as supplementary guidance. They do not guarantee college admission outcomes. Educational counselors should exercise professional judgment when advising students based on these reports.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a192f] mb-3">7. Intellectual Property</h2>
            <p>The Service, including its design, features, and content, is owned by TheStudentBlueprint. Agency partners receive a license to use the platform and white-label features according to their subscription plan. Student data remains the property of the respective students and agencies.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a192f] mb-3">8. Limitation of Liability</h2>
            <p>TheStudentBlueprint is provided &quot;as is&quot; without warranties of any kind. We shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a192f] mb-3">9. Termination</h2>
            <p>We may suspend or terminate your account for violation of these terms. Upon termination, your access to the Service will cease and your data may be deleted after a 90-day grace period.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0a192f] mb-3">10. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="mailto:hello@thestudentblueprint.com" className="text-[#c9a227] hover:underline">hello@thestudentblueprint.com</a>.</p>
          </section>
        </div>
      </main>

      <footer className="bg-[#0a192f] py-8 px-6">
        <div className="max-w-4xl mx-auto text-center text-[10px] font-bold text-white/10 uppercase tracking-[0.4em]">
          © {new Date().getFullYear()} TheStudentBlueprint Admissions Consulting
        </div>
      </footer>
    </div>
  )
}
